name: fastboard_flutter
description: A new Flutter package to help developers quickly build whiteboard applications.
version: 0.1.2
homepage: https://github.com/netless-io/fastboard_flutter

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.1.0
    i18n_extension: ^15.0.5
    stream_transform: ^2.1.1
    whiteboard_sdk_flutter: ^0.5.4

dev_dependencies:
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter:
    assets:
        - assets/icons/
