name: fastboard_flutter
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  whiteboard_sdk_flutter: ^0.3.0
  flutter_svg: ^1.0.3
#  whiteboard_sdk_flutter:
#    path: ../whiteboard-flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - icons/fast_ic_tool_scene_add.svg
    - icons/fast_ic_tool_scene_prev.svg
    - icons/fast_ic_tool_scene_next.svg