name: fastboard_flutter
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
    sdk: ">=2.15.1 <3.0.0"
    flutter: ">=1.17.0"

dartfmt:
    line_length: 120

dependencies:
    flutter:
        sdk: flutter
    whiteboard_sdk_flutter: ^0.4.0
#    whiteboard_sdk_flutter:
#        path: ../whiteboard_flutter
    flutter_svg: ^1.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    assets:
        - assets/icons/